name: Execute Shell Script

on:
  push:
    branches:
      - main 

jobs:
  execute_script:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Execute shell script
        run: ./name.sh
