name: CI

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
   run-shellscript:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Run sh file
       run: chmod +x name.sh
     - name: Run file
       run: sh name.sh
