name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'Github Actions Notification'
          body: 'A new commit has been pushed to the main branch.'
          to: 'prathibha.naik1661@cientra.com,hari.prasad1660@cientra.com'
          from: 'ajaykarthick158@gmail.com'
