name: Execute TPT Batch File and Send Email Notification

on:
  push:
    branches:
      - main

jobs:
  execute_tpt:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Execute TPT Batch File
        run: F:\TPT_Examples\01 Getting Started\First_test_01.bat
     
