name: Unit-selection

on:
  workflow_dispatch:
    inputs:
      input_params: input_params.json
        description: 'Input Parameters'
        required: true
        type: file

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read Input Parameters
        id: read_inputs
        run: |
          echo "::set-output name=inputs::$(cat ${{ github.event.inputs.input_params }})"

      - name: Use Input Parameters
        run: |
          inputs=$(echo "${{ steps.read_inputs.outputs.inputs }}")

          # Access the individual inputs as needed
          echo "Input 1: $(echo "$inputs" | jq -r .input1)"
          echo "Input 2: $(echo "$inputs" | jq -r .input2)"
          echo "Input 3: $(echo "$inputs" | jq -r .input3)"
          echo "Input 4: $(echo "$inputs" | jq -r .input4)"
          echo "Input 5: $(echo "$inputs" | jq -r .input5)"

      # Rest of your workflow steps...
